### ISSUE TITLE
request: event throttling

### ISSUE THREAD

**Issue by gamecubate** [piranha/keybind#4]
Cool lib. Thanks for this. Not 100% sure that this request is in-domain but I would like to be able to throttle bound key events to a certain rate. Of course I could do this downstream, within each event handler. Still, I'd like to request a feature for this. Perfectly okay with me if you reject on grounds of ill-fit.

**Comment by gamecubate** [comment]
It's more complicated than that. Will close this issue because my needs go beyond what this was designed to provide.

**Comment by sansolovyov** [comment]
ok :-)
