### ISSUE TITLE
Emacs style keystrings aren't working

### ISSUE THREAD

**Issue by shen-tian** [piranha/keybind#5]
Thanks for this! Having a quick try, and it seems that this kind of code doesn't work right now?

     (key/bind! "C-c C-x j" ::chord #(js/alert "ever heard of emacs chords?"))

getting an error like

    Error: Unknown modified 'C' in keystring 'C-c'

was this in an older version? Or on the todo list?

**Comment by sansolovyov** [comment]
Well, I looked at history of the project and it seems it's my wishful thinking. Anyway, somehow I got dragged into implementing that, so enjoy 2.2.0! :)

**Comment by shen-tian** [comment]
Amazing. Thanks! That made my Saturday morning :)
